baseURL = "https://oo8a.com/"
languageCode = "zh-CN"
title = "oo8a"
theme = "liquorice"
publishDir = "docs"
copyright = "本作品采用知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可。"

[params]
    author = "wz"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
      style = "dracula"